export const CATEGORIES = [
  {
    id: "diseno",
    title: "Diseño Gráfico",
    blurb: "Logos, manual de marca, posts de Instagram, packaging e impresos.",
    icon: "palette",
    popularTags: ["diseñador de logo", "branding", "packaging", "posts para redes"],
    color: "#2563EB",
  },
  {
    id: "web",
    title: "Desarrollo Web",
    blurb: "Landings, páginas web en React/WordPress, tiendas online y pasarelas.",
    icon: "code",
    popularTags: ["página web", "landing page", "tienda online", "wordpress"],
    color: "#1D4ED8",
  },
  {
    id: "marketing",
    title: "Marketing Digital",
    blurb: "Campañas de Meta Ads, TikToks, guiones de Reels y estrategia de ventas.",
    icon: "rocket",
    popularTags: ["meta ads", "reels tiktok", "calendario contenido", "google ads"],
    color: "#F97316",
  },
  {
    id: "admin",
    title: "Administración",
    blurb: "Kardex, Excel avanzado, reportes para SUNAT, costeo y cotizaciones.",
    icon: "table",
    popularTags: ["excel sunat", "costeo de precios", "kardex inventario", "flujo de caja"],
    color: "#16A34A",
  },
  {
    id: "idiomas",
    title: "Idiomas",
    blurb: "Clases 1:1 de inglés para atender clientes, traducción de cartas y web.",
    icon: "languages",
    popularTags: ["clases de inglés", "traducción", "inglés para negocios", "revisión textos"],
    color: "#7C3AED",
  },
] as const;

export const UNIVERSITIES = [
  "Todas",
  "UTP",
  "UPC",
  "PUCP",
  "UNMSM",
  "UNI",
  "USIL",
  "Universidad de Lima",
  "UNALM",
] as const;

export const CAREERS = [
  "Diseño Gráfico",
  "Ingeniería de Sistemas",
  "Ingeniería de Software",
  "Marketing y Comunicaciones",
  "Administración de Empresas",
  "Comunicaciones",
  "Traducción e Interpretación",
  "Economía",
  "Otra",
];

export const STUDENT_STEPS = [
  { n: 1, label: "Rol" },
  { n: 2, label: "Datos" },
  { n: 3, label: "Carné" },
  { n: 4, label: "Verificación" },
];

export type PortfolioShot = {
  id: string;
  title: string;
  category: string;
  tag: string;
  gradient: string;
  accentColor: string;
  iconType: "logo" | "web" | "app" | "excel" | "ad" | "translate" | "photo";
  deliverables: string[];
  clientQuote?: string;
  clientName?: string;
  timeSpent?: string;
};

export type ServiceOffering = {
  id: string;
  title: string;
  priceFrom: number;
  deliveryDays: string;
  description: string;
  popular?: boolean;
  deliverables: string[];
};

export type StudentReview = {
  id: string;
  author: string;
  business: string;
  rating: number;
  date: string;
  serviceTitle: string;
  comment: string;
};

export type StudentVerification = {
  carneUniversitario: boolean;
  identidadDni: boolean;
  telefonoWhatsapp: boolean;
  cuentaEscrow: boolean;
  fechaVerificacion: string;
  universidadConstancia: string;
};

export type Talent = {
  id: string;
  name: string;
  avatarUrl: string;
  university: string;
  career: string;
  semester: string;
  category: string;
  priceFrom: number;
  rating: number;
  reviews: number;
  headline: string;
  bio: string;
  skills: string[];
  colegiado: boolean;
  availableNow: boolean;
  availabilityStatus: "available" | "busy" | "scheduled";
  availabilityNote: string;
  responseTime: string;
  completedJobs: number;
  verifiedStudent: boolean;
  verifications: StudentVerification;
  tags: string[];
  initials: string;
  avatarBg: string;
  services: ServiceOffering[];
  portfolio: PortfolioShot[];
  reviewsList: StudentReview[];
};

export const POPULAR_SEARCH_SUGGESTIONS = [
  "diseñador de logo",
  "clases de inglés",
  "página web",
  "excel sunat",
  "meta ads",
  "packaging comida",
  "tienda virtual",
  "costeo de precios",
];

export const TALENT: Talent[] = [
  {
    id: "camila",
    name: "Camila Rojas",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    university: "UTP",
    career: "Diseño Gráfico",
    semester: "7.º semestre",
    category: "Diseño Gráfico",
    priceFrom: 45,
    rating: 4.9,
    reviews: 18,
    headline: "Identidad visual y logos memorables para MYPES que empiezan a vender online.",
    bio: "Hola, soy Camila. Estudio el 7.º ciclo de Diseño Gráfico en la UTP. Me especializo en crear marcas con personalidad para negocios de comida, cafeterías y tiendas de barrio. En cada proyecto entrego archivos vectoriales originales, paleta de color y plantillas editables en Canva para que tu negocio sea autónomo. Trabajo bajo la modalidad de mini-sustentación: te explico el porqué de cada propuesta antes de finalizar.",
    skills: ["Adobe Illustrator", "Canva Pro", "Figma", "Branding Gastronómico", "Diseño Editorial", "Identidad Corporativa", "Packaging"],
    colegiado: false,
    availableNow: true,
    availabilityStatus: "available",
    availabilityNote: "🟢 Disponible hoy · Responde en menos de 1 hora",
    responseTime: "< 1 hora",
    completedJobs: 24,
    verifiedStudent: true,
    verifications: {
      carneUniversitario: true,
      identidadDni: true,
      telefonoWhatsapp: true,
      cuentaEscrow: true,
      fechaVerificacion: "15 de Mayo 2026",
      universidadConstancia: "UTP - Matrícula 2026-I Activa",
    },
    tags: ["logo", "diseñador de logo", "marca", "branding", "posts", "cevichería", "identidad visual"],
    initials: "CR",
    avatarBg: "from-blue-600 to-indigo-600",
    services: [
      {
        id: "srv-c1",
        title: "Diseño de Logotipo Principal & Paleta de Color",
        priceFrom: 45,
        deliveryDays: "3 a 4 días",
        popular: true,
        description: "Creación de 3 rutas visuales de logotipo desde cero, manual de colores primarios/secundarios y tipografías recomendadas.",
        deliverables: [
          "Logo vectorial en AI, SVG, PNG fondo transparente",
          "Versión horizontal, vertical y favicons para redes",
          "Paleta cromática con códigos HEX y CMYK para imprenta",
          "Mini-sustentación explicativa de 10 min por Zoom o WhatsApp",
        ],
      },
      {
        id: "srv-c2",
        title: "Pack de 12 Plantillas Editables en Canva",
        priceFrom: 60,
        deliveryDays: "3 días",
        description: "Plantillas modulares para promociones, ofertas del día y testimonios, listas para que tú mismo cambies fotos y precios.",
        deliverables: [
          "12 artes editables en enlace directo de Canva",
          "6 historias destacadas con iconos a medida",
          "Guía básica en PDF para mantener la armonía visual",
        ],
      },
      {
        id: "srv-c3",
        title: "Carta Menú Digital + Código QR para Mesas",
        priceFrom: 35,
        deliveryDays: "48 horas",
        description: "Diseño de menú gastronómico ordenado por secciones, con precios claros y versión ligera para enviar por chat.",
        deliverables: [
          "Diseño en formato A4 / Díptico en alta resolución",
          "PDF interactivo optimizado para WhatsApp",
          "Sticker listo con QR vectorizado para imprimir en vinil",
        ],
      },
    ],
    portfolio: [
      {
        id: "camila-1",
        title: "Identidad Visual 'Mar & Ají'",
        category: "Branding Gastronómico",
        tag: "Logo + Paleta",
        gradient: "from-blue-600 via-indigo-700 to-slate-900",
        accentColor: "#F97316",
        iconType: "logo",
        deliverables: ["Logo vectorial SVG/PNG", "Manual de marca simplificado", "3 plantillas Canva para post"],
        clientQuote: "Me diseñó el logo en 4 días y me explicó la justificación de colores paso a paso.",
        clientName: "Rosa M. (Cevichería en Magdalena)",
        timeSpent: "4 días",
      },
      {
        id: "camila-2",
        title: "Pack 12 Posts Promocionales",
        category: "Redes Sociales",
        tag: "Plantillas Canva",
        gradient: "from-orange-500 via-amber-600 to-rose-600",
        accentColor: "#FFFFFF",
        iconType: "ad",
        deliverables: ["12 artes editables", "Historias destacadas", "Tipografías listas"],
        clientQuote: "Super puntual y adaptable a las correcciones que pedimos.",
        clientName: "Andrea C. (Boutique SJL)",
        timeSpent: "3 días",
      },
      {
        id: "camila-3",
        title: "Carta Menú Digital + QR",
        category: "Diseño Editorial",
        tag: "Menú Imprimible / PDF",
        gradient: "from-slate-800 via-blue-900 to-cyan-900",
        accentColor: "#22C55E",
        iconType: "photo",
        deliverables: ["Carta A4 alta resolución", "Versión optimizada para WhatsApp", "Sticker QR para mesa"],
        clientQuote: "El código QR quedó listo para imprimir en vinil adhesivo.",
        clientName: "Jorge L. (Cafetería Lince)",
        timeSpent: "2 días",
      },
      {
        id: "camila-4",
        title: "Manual de Marca MYPE Textil",
        category: "Branding Moda",
        tag: "Manual 12 Págs",
        gradient: "from-purple-900 via-indigo-800 to-slate-900",
        accentColor: "#E879F9",
        iconType: "logo",
        deliverables: ["Usos correctos e incorrectos del logo", "Tipografías para web y estampados", "Muestrario de tags para prendas"],
        clientName: "Gamarra Trend",
        timeSpent: "5 días",
      },
    ],
    reviewsList: [
      {
        id: "rev-c1",
        author: "Rosa Mendoza",
        business: "Cevichería 'Mar & Ají' · Magdalena",
        rating: 5,
        date: "Hace 4 días",
        serviceTitle: "Diseño de Logotipo Principal & Paleta de Color",
        comment: "Excelente disposición. Me envió 3 propuestas muy bien explicadas y no paramos hasta que el isotipo quedó perfecto. El pago en escrow me dio mucha seguridad.",
      },
      {
        id: "rev-c2",
        author: "Andrea Castillo",
        business: "Boutique de Ropa · SJL",
        rating: 5,
        date: "Hace 2 semanas",
        serviceTitle: "Pack de 12 Plantillas Editables en Canva",
        comment: "Las plantillas en Canva me salvaron la vida. Ahora puedo publicar mis promociones semanales en minutos sin depender de nadie.",
      },
      {
        id: "rev-c3",
        author: "Jorge Lozano",
        business: "Cafetería La Esquina · Lince",
        rating: 4.8,
        date: "Hace 1 mes",
        serviceTitle: "Carta Menú Digital + Código QR para Mesas",
        comment: "Muy rápida en responder los mensajes y super ordenada con las listas de insumos. 100% recomendada para cualquier MYPE.",
      },
    ],
  },
  {
    id: "diego",
    name: "Diego Palacios",
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&auto=format&fit=crop&q=80",
    university: "UNI",
    career: "Ingeniería de Sistemas",
    semester: "9.º semestre",
    category: "Desarrollo Web",
    priceFrom: 60,
    rating: 4.8,
    reviews: 12,
    headline: "Páginas web rápidas y landings que convierten clics en pedidos de WhatsApp.",
    bio: "Estudiante del 9.º ciclo en la Universidad Nacional de Ingeniería (UNI). Construyo páginas web ligeras con React, Next.js y Tailwind CSS. No uso constructores pesados que hacen lenta tu web: programo código limpio enfocado en que los clientes que entran desde su celular te escriban directamente a WhatsApp con un solo toque.",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "WhatsApp Cloud API", "SEO Local", "Google Analytics"],
    colegiado: false,
    availableNow: true,
    availabilityStatus: "available",
    availabilityNote: "🟢 Disponible hoy · Responde en menos de 30 min",
    responseTime: "< 30 min",
    completedJobs: 17,
    verifiedStudent: true,
    verifications: {
      carneUniversitario: true,
      identidadDni: true,
      telefonoWhatsapp: true,
      cuentaEscrow: true,
      fechaVerificacion: "28 de Mayo 2026",
      universidadConstancia: "UNI - FIIS Matrícula 2026-I",
    },
    tags: ["página web", "landing page", "web", "sitio web", "react", "whatsapp", "taller"],
    initials: "DP",
    avatarBg: "from-blue-700 to-cyan-600",
    services: [
      {
        id: "srv-d1",
        title: "Landing Page One-Page de Alta Conversión",
        priceFrom: 60,
        deliveryDays: "5 a 7 días",
        popular: true,
        description: "Sitio web de una página diseñado para promocionar un producto o servicio específico y captar leads directos a WhatsApp.",
        deliverables: [
          "Desarrollo frontend responsivo en React + Vite",
          "Botón cotizador flotante configurado a tu número",
          "Integración de Google Maps y formulario de contacto",
          "Despliegue gratuito en Vercel o Netlify con tu dominio .pe o .com",
        ],
      },
      {
        id: "srv-d2",
        title: "Catálogo Online de Productos con Carrito Simple",
        priceFrom: 90,
        deliveryDays: "7 a 10 días",
        description: "Catálogo interactivo con buscador y filtro por categorías. El cliente añade productos y envía el pedido armado a tu WhatsApp.",
        deliverables: [
          "Catálogo autogestionable mediante Google Sheets",
          "Resumen automático de pedido con precio total",
          "Optimización de velocidad (puntuación > 90 en Google PageSpeed)",
        ],
      },
      {
        id: "srv-d3",
        title: "Optimización de Carga & SEO Local Google",
        priceFrom: 40,
        deliveryDays: "48 horas",
        description: "Mejora de velocidad de tu web actual para que cargue en menos de 2 segundos en celulares y aparezca en búsquedas de Lima.",
        deliverables: [
          "Compresión de imágenes a formato WebP",
          "Configuración de etiquetas meta OpenGraph y Schema.org",
          "Reporte antes y después de métricas Core Web Vitals",
        ],
      },
    ],
    portfolio: [
      {
        id: "diego-1",
        title: "Landing Page Taller Automotriz",
        category: "Desarrollo Frontend",
        tag: "Web + WhatsApp API",
        gradient: "from-slate-900 via-cyan-950 to-blue-900",
        accentColor: "#22C55E",
        iconType: "web",
        deliverables: ["Landing responsiva con carga ultra rápida", "Botón flotante cotizador a WhatsApp", "Hosting y dominio configurados"],
        clientQuote: "El escrow me dio total tranquilidad: no pagué hasta verla en vivo con mi dominio.",
        clientName: "Héctor V. (MYPE Villa El Salvador)",
        timeSpent: "6 días",
      },
      {
        id: "diego-2",
        title: "Catálogo Online de Repuestos",
        category: "E-Commerce Ligero",
        tag: "Catálogo con Carrito",
        gradient: "from-blue-600 via-indigo-800 to-slate-900",
        accentColor: "#F97316",
        iconType: "app",
        deliverables: ["Filtro por marca y modelo", "Exportación de cotización a PDF", "Panel de administración sencillo"],
        clientQuote: "Mis clientes ahora me mandan la captura del repuesto exacto.",
        clientName: "Carlos R. (Repuestos Surquillo)",
        timeSpent: "7 días",
      },
      {
        id: "diego-3",
        title: "Formulario de Reserva con Notificación",
        category: "Automatización Web",
        tag: "React + Tailwind",
        gradient: "from-indigo-900 via-blue-800 to-teal-800",
        accentColor: "#38BDF8",
        iconType: "web",
        deliverables: ["Formulario validado contra spam", "Email automático de confirmación"],
        clientName: "Dra. Patricia S. (Consultorio Dental)",
        timeSpent: "2 días",
      },
    ],
    reviewsList: [
      {
        id: "rev-d1",
        author: "Héctor Valdivia",
        business: "Taller Mecánico 'El Profe' · Villa El Salvador",
        rating: 5,
        date: "Hace 1 semana",
        serviceTitle: "Landing Page One-Page de Alta Conversión",
        comment: "Excelente programador. Mi taller no tenía presencia web y ahora los choferes de la zona me ubican por Google y me escriben por WhatsApp.",
      },
      {
        id: "rev-d2",
        author: "Carlos Ruiz",
        business: "Distribuidora de Repuestos · Surquillo",
        rating: 4.8,
        date: "Hace 3 semanas",
        serviceTitle: "Catálogo Online de Productos con Carrito Simple",
        comment: "El catálogo que armó Diego funciona perfecto. Lo mejor fue que me enseñó a cambiar precios desde un Excel de Google.",
      },
    ],
  },
  {
    id: "valeria",
    name: "Valeria Quispe",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80",
    university: "PUCP",
    career: "Marketing y Comunicaciones",
    semester: "8.º semestre",
    category: "Marketing Digital",
    priceFrom: 50,
    rating: 5.0,
    reviews: 14,
    headline: "Campañas de Meta Ads y calendario de contenido para negocios con poco presupuesto.",
    bio: "Estudio Marketing en la PUCP (8.º ciclo). Ayudo a microempresas y profesionales independientes a sacarle el jugo a presupuestos publicitarios desde S/ 10 al día en Facebook, Instagram y TikTok. No te prometo fórmulas mágicas: te entrego segmentaciones reales, copys probados y reportes transparentes.",
    skills: ["Meta Ads Manager", "TikTok Ads", "Copywriting", "Estrategia de Contenidos", "Google Analytics 4", "CapCut"],
    colegiado: false,
    availableNow: false,
    availabilityStatus: "scheduled",
    availabilityNote: "🟡 Acepta reservas para entregas a partir del 28 de Agosto",
    responseTime: "< 2 horas",
    completedJobs: 19,
    verifiedStudent: true,
    verifications: {
      carneUniversitario: true,
      identidadDni: true,
      telefonoWhatsapp: true,
      cuentaEscrow: true,
      fechaVerificacion: "10 de Junio 2026",
      universidadConstancia: "PUCP - FCCyA Matrícula Regular",
    },
    tags: ["meta ads", "ads", "facebook ads", "instagram", "contenido", "marketing", "reels tiktok"],
    initials: "VQ",
    avatarBg: "from-orange-600 to-amber-600",
    services: [
      {
        id: "srv-v1",
        title: "Configuración & Lanzamiento de Campaña Meta Ads",
        priceFrom: 50,
        deliveryDays: "4 días",
        popular: true,
        description: "Estructuración de campaña publicitaria en Facebook e Instagram segmentada en tu distrito para conseguir mensajes y clientes.",
        deliverables: [
          "Segmentación detallada por ubicación y comportamientos",
          "Redacción de 3 variantes de copy publicitario de alto impacto",
          "Configuración de Pixel y eventos de WhatsApp",
          "Supervisión y optimización durante 7 días",
        ],
      },
      {
        id: "srv-v2",
        title: "Calendario Mensual de 20 Guiones para Reels/TikTok",
        priceFrom: 70,
        deliveryDays: "5 días",
        description: "Guiones estructurados con gancho inicial (hook), desarrollo y llamada a la acción para grabar fácilmente con tu celular.",
        deliverables: [
          "20 guiones redactados con ideas visuales y audios en tendencia",
          "Estructura de llamados a la acción para captar números",
          "Plantilla de Notion o Excel para organizar la grabación",
        ],
      },
    ],
    portfolio: [
      {
        id: "valeria-1",
        title: "Campaña Meta Ads para Tienda de Ropa",
        category: "Paid Social",
        tag: "ROAS 3.8x",
        gradient: "from-rose-600 via-orange-600 to-amber-500",
        accentColor: "#FFFFFF",
        iconType: "ad",
        deliverables: ["Segmentación de público en Lima", "3 variantes de creativos con copy persuasivo", "Reporte semanal de métricas"],
        clientQuote: "Gasté solo S/ 150 en pauta y cerramos 32 pedidos en la primera semana.",
        clientName: "Fiorella M. (Gamarra Moda)",
        timeSpent: "5 días",
      },
      {
        id: "valeria-2",
        title: "Calendario Mensual 20 Reels & Posts",
        category: "Content Strategy",
        tag: "Guiones con Hooks",
        gradient: "from-amber-600 via-orange-700 to-red-800",
        accentColor: "#FDE047",
        iconType: "ad",
        deliverables: ["20 guiones con gancho y llamada a la acción", "Guía de grabación con celular", "Hashtags y horarios recomendados"],
        clientName: "Matías K. (Gimnasio San Miguel)",
        timeSpent: "4 días",
      },
    ],
    reviewsList: [
      {
        id: "rev-v1",
        author: "Fiorella Morales",
        business: "Gamarra Moda Femenina · La Victoria",
        rating: 5,
        date: "Hace 5 días",
        serviceTitle: "Configuración & Lanzamiento de Campaña Meta Ads",
        comment: "Valeria entiende muy bien cómo vender en redes. Con poco presupuesto de prueba logramos llenar nuestro WhatsApp de clientas interesadas.",
      },
    ],
  },
  {
    id: "renzo",
    name: "Renzo Huamán",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
    university: "UNMSM",
    career: "Administración de Empresas",
    semester: "10.º semestre",
    category: "Administración",
    priceFrom: 35,
    rating: 4.8,
    reviews: 21,
    headline: "Kardex en Excel, control de inventario y tablas listas para declarar a SUNAT.",
    bio: "Estudiante del 10.º ciclo de Administración en la Universidad Nacional Mayor de San Marcos (UNMSM). Ordeno el caos operativo de micro y pequeñas empresas: inventarios desactualizados, pérdidas de stock y planillas desordenadas. Creo plantillas automatizadas con fórmulas de Excel que cualquier persona puede usar sin enredarse.",
    skills: ["Excel Avanzado (VBA/Macros)", "Control de Inventarios (Kardex)", "Costeo Gastronómico", "Facturación SUNAT", "Flujo de Caja"],
    colegiado: false,
    availableNow: true,
    availabilityStatus: "available",
    availabilityNote: "🟢 Disponible hoy · Responde en menos de 15 min",
    responseTime: "< 15 min",
    completedJobs: 33,
    verifiedStudent: true,
    verifications: {
      carneUniversitario: true,
      identidadDni: true,
      telefonoWhatsapp: true,
      cuentaEscrow: true,
      fechaVerificacion: "02 de Junio 2026",
      universidadConstancia: "UNMSM - FCA Constancia de Matrícula",
    },
    tags: ["excel sunat", "kardex inventario", "excel", "sunat", "inventario", "costos", "admin"],
    initials: "RH",
    avatarBg: "from-emerald-600 to-green-700",
    services: [
      {
        id: "srv-r1",
        title: "Plantilla Automatizada de Kardex e Inventario",
        priceFrom: 35,
        deliveryDays: "48 horas",
        popular: true,
        description: "Control de entradas, salidas y stock en tiempo real mediante método promedio ponderado, con alertas automáticas de reposición.",
        deliverables: [
          "Archivo Excel (.xlsx) con fórmulas protegidas",
          "Alerta visual en color rojo cuando el stock está bajo",
          "Video tutorial grabado de 5 minutos explicando su uso",
        ],
      },
      {
        id: "srv-r2",
        title: "Flujo de Caja Proyectado a 6 Meses",
        priceFrom: 50,
        deliveryDays: "3 días",
        description: "Modelo financiero para proyectar ingresos, costos fijos y gastos variables, con cálculo automático de utilidad neta y punto de equilibrio.",
        deliverables: [
          "Dashboard con gráficos dinámicos de barras y pastel",
          "Simulador de escenarios optimista, moderado y pesimista",
        ],
      },
    ],
    portfolio: [
      {
        id: "renzo-1",
        title: "Plantilla Kardex Automatizada",
        category: "Excel & Finanzas",
        tag: "Macros + Alertas",
        gradient: "from-emerald-900 via-teal-800 to-green-950",
        accentColor: "#86EFAC",
        iconType: "excel",
        deliverables: ["Kardex promedio ponderado", "Alerta automática de stock mínimo", "Manual en video de 5 minutos"],
        clientQuote: "Tenía un desorden tremendo con el stock de mi ferretería. Me lo dejó impecable.",
        clientName: "Don Guillermo (Ferretería Ate)",
        timeSpent: "3 días",
      },
      {
        id: "renzo-2",
        title: "Flujo de Caja Proyectado 6 Meses",
        category: "Planeamiento Financiero",
        tag: "Dashboard Financiero",
        gradient: "from-teal-800 via-emerald-700 to-cyan-800",
        accentColor: "#FFFFFF",
        iconType: "excel",
        deliverables: ["Ingresos vs egresos proyectados", "Gráficos dinámicos para socios", "Calculadora de punto de equilibrio"],
        clientName: "Luciana B. (Restaurante Barranco)",
        timeSpent: "4 días",
      },
    ],
    reviewsList: [
      {
        id: "rev-r1",
        author: "Don Guillermo Palomino",
        business: "Ferretería 'San Judas' · Ate",
        rating: 5,
        date: "Hace 1 semana",
        serviceTitle: "Plantilla Automatizada de Kardex e Inventario",
        comment: "Puntual y muy didáctico. Me dejó el archivo funcionando en mi laptop antigua y me explicó con paciencia cómo ingresar las boletas.",
      },
    ],
  },
  {
    id: "lucia",
    name: "Lucía Ferrer",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80",
    university: "UPC",
    career: "Traducción e Interpretación",
    semester: "6.º semestre",
    category: "Idiomas",
    priceFrom: 40,
    rating: 4.9,
    reviews: 16,
    headline: "Traducción EN–ES y clases de inglés conversacional para atender turistas y clientes extranjeros.",
    bio: "Estudiante de Traducción e Interpretación en la UPC (6.º ciclo) con certificación Cambridge C2 Proficiency. Ofrezco traducción fiel de contenidos web, menús gastronómicos y cartas de presentación, además de sesiones prácticas 1 a 1 de inglés conversacional para personal de atención al cliente.",
    skills: ["Inglés Nativo / C2", "Traducción Gastronómica", "Inglés Comercial", "Revisión de Textos", "Roleplay Conversacional"],
    colegiado: false,
    availableNow: true,
    availabilityStatus: "available",
    availabilityNote: "🟢 Disponible hoy · Responde en menos de 1 hora",
    responseTime: "< 1 hora",
    completedJobs: 22,
    verifiedStudent: true,
    verifications: {
      carneUniversitario: true,
      identidadDni: true,
      telefonoWhatsapp: true,
      cuentaEscrow: true,
      fechaVerificacion: "18 de Abril 2026",
      universidadConstancia: "UPC - Carné Universitario Activo",
    },
    tags: ["clases de inglés", "traducción", "inglés", "traducción de textos", "turistas", "idiomas"],
    initials: "LF",
    avatarBg: "from-purple-600 to-violet-700",
    services: [
      {
        id: "srv-l1",
        title: "Traducción Profesional de Menú o Carta Gastronómica",
        priceFrom: 40,
        deliveryDays: "48 horas",
        popular: true,
        description: "Traducción contextualizada de platos típicos e ingredientes peruanos con descripciones atractivas para turistas.",
        deliverables: [
          "Documento bilingüe revisado gramaticalmente",
          "Glosario de términos culinarios peruanos",
          "Ajustes posteriores si cambias precios o platos",
        ],
      },
      {
        id: "srv-l2",
        title: "Pack 4 Clases de Inglés Conversacional para Negocios",
        priceFrom: 80,
        deliveryDays: "2 semanas",
        description: "Sesiones de 45 minutos por Zoom enfocadas en saludos, preguntas de turistas, formas de pago y resolución de quejas.",
        deliverables: [
          "4 sesiones individuales en vivo",
          "Fichas de vocabulario en PDF",
          "Audios de práctica para repasar pronunciación",
        ],
      },
    ],
    portfolio: [
      {
        id: "lucia-1",
        title: "Menú Gastronómico Inglés/Español",
        category: "Traducción Culinaria",
        tag: "Menú Turístico",
        gradient: "from-purple-950 via-indigo-900 to-violet-900",
        accentColor: "#C4B5FD",
        iconType: "translate",
        deliverables: ["Glosario de ingredientes peruanos traducidos", "Menú bilingüe con términos amigables", "Revisión nativa de gramática"],
        clientQuote: "Los turistas en Cusco ahora entienden perfectamente los platos típicos.",
        clientName: "Mario E. (Hostal & Resto Cusco)",
        timeSpent: "2 días",
      },
    ],
    reviewsList: [
      {
        id: "rev-l1",
        author: "Mario Espinoza",
        business: "Hostal & Café 'Qorikancha' · Cusco",
        rating: 5,
        date: "Hace 2 semanas",
        serviceTitle: "Traducción Profesional de Menú o Carta Gastronómica",
        comment: "Lucía tradujo nuestro menú en tiempo récord y con términos muy naturales para extranjeros. Los turistas no dudan al ordenar.",
      },
    ],
  },
  {
    id: "andres",
    name: "Andrés Paredes",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80",
    university: "UNI",
    career: "Ingeniería de Software",
    semester: "8.º semestre",
    category: "Desarrollo Web",
    priceFrom: 70,
    rating: 4.9,
    reviews: 16,
    headline: "Sitios web y apps a medida con React y Next.js. Entrego código limpio y optimizado para Google.",
    bio: "Estudiante de 8.º ciclo de Ingeniería de Software en la UNI. Creo soluciones web a medida con arquitectura moderna: interfaces limpias, carga instantánea y paneles de administración claros. Ideal si ya tienes un diseño en Figma y necesitas llevarlo a código real sin fallas.",
    skills: ["React", "Next.js", "TypeScript", "Node.js", "PostgreSQL", "Figma to Code", "Git"],
    colegiado: false,
    availableNow: true,
    availabilityStatus: "available",
    availabilityNote: "🟢 Disponible hoy · Responde en menos de 45 min",
    responseTime: "< 45 min",
    completedJobs: 20,
    verifiedStudent: true,
    verifications: {
      carneUniversitario: true,
      identidadDni: true,
      telefonoWhatsapp: true,
      cuentaEscrow: true,
      fechaVerificacion: "12 de Mayo 2026",
      universidadConstancia: "UNI - Matrícula Verificada",
    },
    tags: ["página web", "react", "nextjs", "frontend", "web", "programador", "landing page"],
    initials: "AP",
    avatarBg: "from-teal-600 to-cyan-700",
    services: [
      {
        id: "srv-a1",
        title: "Página Web Corporativa Multi-Sección con React",
        priceFrom: 85,
        deliveryDays: "7 días",
        popular: true,
        description: "Sitio web completo con sección de inicio, servicios, testimonios, blog y formulario de cotización conectado a tu correo.",
        deliverables: [
          "Código fuente completo en repositorio GitHub",
          "Diseño 100% responsivo y testeado en móviles",
          "SEO On-Page y rendimiento 95+ en Lighthouse",
        ],
      },
    ],
    portfolio: [
      {
        id: "andres-1",
        title: "Web Corporativa con Sistema de Citas",
        category: "Desarrollo Fullstack",
        tag: "React + Calendario",
        gradient: "from-teal-950 via-slate-900 to-cyan-900",
        accentColor: "#5EEAD4",
        iconType: "web",
        deliverables: ["Selector de fechas y horarios disponibles", "Sincronización con Google Calendar", "SEO técnico para aparecer en Google"],
        clientQuote: "La entrega fue exacta en el plazo y me dejó un tutorial para cambiar los textos.",
        clientName: "Dra. Sofía R. (Centro de Terapia)",
        timeSpent: "8 días",
      },
    ],
    reviewsList: [
      {
        id: "rev-a1",
        author: "Dra. Sofía Ramos",
        business: "Centro Psicológico 'Aprender' · San Borja",
        rating: 5,
        date: "Hace 1 mes",
        serviceTitle: "Página Web Corporativa Multi-Sección con React",
        comment: "Andrés es un excelente profesional técnico. Nos entregó la web antes de tiempo y todo funciona como un reloj.",
      },
    ],
  },
  {
    id: "sofia",
    name: "Sofía León",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&auto=format&fit=crop&q=80",
    university: "Universidad de Lima",
    career: "Diseño Gráfico",
    semester: "5.º semestre",
    category: "Diseño Gráfico",
    priceFrom: 38,
    rating: 4.6,
    reviews: 11,
    headline: "Diseño de logotipos frescos, packaging y piezas publicitarias listas para imprimir.",
    bio: "Estudiante de Diseño en la Universidad de Lima (5.º ciclo). Mi pasión es el empaque y la imagen de producto. Si vendes alimentos, cosmética o productos artesanales, te ayudo a crear etiquetas llamativas con líneas de troquel exactas para imprenta.",
    skills: ["Diseño de Packaging", "Adobe InDesign", "Illustrator", "Troqueles y CMYK", "Mockups 3D"],
    colegiado: false,
    availableNow: true,
    availabilityStatus: "available",
    availabilityNote: "🟢 Disponible hoy · Responde en menos de 2 horas",
    responseTime: "< 2 horas",
    completedJobs: 15,
    verifiedStudent: true,
    verifications: {
      carneUniversitario: true,
      identidadDni: true,
      telefonoWhatsapp: true,
      cuentaEscrow: true,
      fechaVerificacion: "20 de Mayo 2026",
      universidadConstancia: "U. de Lima - Carné Universitario",
    },
    tags: ["diseñador de logo", "packaging", "logo", "etiquetas", "packaging comida", "marca"],
    initials: "SL",
    avatarBg: "from-pink-600 to-rose-700",
    services: [
      {
        id: "srv-s1",
        title: "Diseño de Etiqueta o Empaque para Producto",
        priceFrom: 38,
        deliveryDays: "3 días",
        popular: true,
        description: "Diseño frontal, reverso y tabla de contenido con medidas exactas de tu envase o bolsa kraft.",
        deliverables: [
          "Archivo vectorial con línea de troquel para imprenta",
          "Modo de color CMYK de alta resolución (300 DPI)",
          "Mockup 3D realista para usar en tus redes",
        ],
      },
    ],
    portfolio: [
      {
        id: "sofia-1",
        title: "Packaging y Etiquetas para Miel Artesanal",
        category: "Diseño de Empaques",
        tag: "Troqueles Listos",
        gradient: "from-pink-900 via-rose-950 to-amber-900",
        accentColor: "#FDE047",
        iconType: "photo",
        deliverables: ["Etiqueta frontal y de información nutricional", "Línea de troquel para imprenta en CMYK", "Mockup 3D para tienda online"],
        clientQuote: "La imprenta no tuvo ninguna observación, los archivos vinieron impecables.",
        clientName: "Apícola Oxapampa",
        timeSpent: "4 días",
      },
    ],
    reviewsList: [
      {
        id: "rev-s1",
        author: "Manuel Delgado",
        business: "Apícola Oxapampa · Lima",
        rating: 5,
        date: "Hace 3 semanas",
        serviceTitle: "Diseño de Etiqueta o Empaque para Producto",
        comment: "El diseño de la etiqueta superó nuestras expectativas. La imprenta no tuvo ninguna queja técnica y el frasco se ve super premium.",
      },
    ],
  },
  {
    id: "mateo",
    name: "Mateo Salas",
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80",
    university: "USIL",
    career: "Ingeniería de Software",
    semester: "9.º semestre",
    category: "Desarrollo Web",
    priceFrom: 55,
    rating: 4.7,
    reviews: 9,
    headline: "Tiendas virtuales con catálogo rápido, cobro con Yape/Plin y pasarela Culqi/Niubiz.",
    bio: "Estudio Ingeniería de Software en USIL (9.º ciclo). Desarrollador enfocado en e-commerce para negocios peruanos con integración nativa de Yape, Plin y pasarelas con tarjeta.",
    skills: ["E-Commerce", "Culqi / Niubiz", "React", "Node.js", "Bases de Datos"],
    colegiado: false,
    availableNow: false,
    availabilityStatus: "scheduled",
    availabilityNote: "🟡 Ocupado hasta el 26 de Agosto",
    responseTime: "< 4 horas",
    completedJobs: 13,
    verifiedStudent: true,
    verifications: {
      carneUniversitario: true,
      identidadDni: true,
      telefonoWhatsapp: true,
      cuentaEscrow: true,
      fechaVerificacion: "15 de Junio 2026",
      universidadConstancia: "USIL - Constancia Regular",
    },
    tags: ["tienda virtual", "página web", "yape plin", "ecommerce", "web", "pasarela"],
    initials: "MS",
    avatarBg: "from-blue-800 to-indigo-900",
    services: [
      {
        id: "srv-m1",
        title: "Tienda Virtual Rápida con Pagos Yape/Plin",
        priceFrom: 55,
        deliveryDays: "7 días",
        popular: true,
        description: "Tienda online con gestión de inventario, tallas/colores y recepción de comprobantes automáticos.",
        deliverables: [
          "Catálogo de hasta 30 productos cargados",
          "Pasarela de pago y botón Yape/Plin",
          "Capacitación de 30 min para cargar productos",
        ],
      },
    ],
    portfolio: [
      {
        id: "mateo-1",
        title: "Tienda de Calzado con Pagos Yape y Tarjeta",
        category: "E-Commerce",
        tag: "Yape + Culqi",
        gradient: "from-blue-950 via-slate-900 to-indigo-900",
        accentColor: "#38BDF8",
        iconType: "web",
        deliverables: ["Carrito de compras optimizado para celular", "Confirmación de comprobante Yape/Plin por WhatsApp", "Gestión de stock por tallas"],
        clientQuote: "En 7 días tenía mi tienda vendiendo en automático.",
        clientName: "Calzados Trujillo (Lima Norte)",
        timeSpent: "7 días",
      },
    ],
    reviewsList: [
      {
        id: "rev-m1",
        author: "Enrique Trujillo",
        business: "Calzados Trujillo · Los Olivos",
        rating: 4.8,
        date: "Hace 2 meses",
        serviceTitle: "Tienda Virtual Rápida con Pagos Yape/Plin",
        comment: "Nos armó la tienda en una semana. Muy atento para resolver dudas.",
      },
    ],
  },
  {
    id: "alicia",
    name: "Alicia Chávez",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80",
    university: "PUCP",
    career: "Economía",
    semester: "8.º semestre",
    category: "Administración",
    priceFrom: 45,
    rating: 4.9,
    reviews: 12,
    headline: "Estructura de costos, precios de venta con margen real y proyecciones para negocios gastronómicos.",
    bio: "Estudiante de Economía en la PUCP (8.º ciclo). Mi objetivo es que los emprendedores dejen de fijar precios 'al ojo'. Calculo tu merma real, costos fijos y costo por porción para garantizar que cada venta te deje ganancia.",
    skills: ["Estructura de Costos", "Fórmulas Financieras", "Excel Avanzado", "Fichas Técnicas", "Punto de Equilibrio"],
    colegiado: false,
    availableNow: true,
    availabilityStatus: "available",
    availabilityNote: "🟢 Disponible hoy · Responde en menos de 1 hora",
    responseTime: "< 1 hora",
    completedJobs: 18,
    verifiedStudent: true,
    verifications: {
      carneUniversitario: true,
      identidadDni: true,
      telefonoWhatsapp: true,
      cuentaEscrow: true,
      fechaVerificacion: "05 de Mayo 2026",
      universidadConstancia: "PUCP - Matrícula 2026-I",
    },
    tags: ["costeo de precios", "excel", "costeo", "finanzas", "márgenes", "admin", "precios"],
    initials: "AC",
    avatarBg: "from-emerald-700 to-teal-800",
    services: [
      {
        id: "srv-ac1",
        title: "Calculadora de Receta Estándar y Margen de Ganancia",
        priceFrom: 45,
        deliveryDays: "3 días",
        popular: true,
        description: "Ficha técnica para hasta 15 platos o productos con merma de ingredientes y precio recomendado para salón y delivery.",
        deliverables: [
          "Excel formulado con costos de insumos actualizados",
          "Margen bruto y neto por producto",
          "Revisión en llamada para resolver dudas",
        ],
      },
    ],
    portfolio: [
      {
        id: "alicia-1",
        title: "Calculadora de Receta Estándar y Costeo",
        category: "Costos Gastronómicos",
        tag: "Margen Bruto Real",
        gradient: "from-emerald-950 via-teal-900 to-slate-900",
        accentColor: "#22C55E",
        iconType: "excel",
        deliverables: ["Ficha técnica con merma de insumos", "Cálculo de precio sugerido por canal (salón vs delivery)", "Sensibilidad al aumento de insumos"],
        clientQuote: "Por fin sé exactamente cuánto gano por cada plato que sale de cocina.",
        clientName: "Renato D. (Dark Kitchen Surco)",
        timeSpent: "4 días",
      },
    ],
    reviewsList: [
      {
        id: "rev-ac1",
        author: "Renato Delgado",
        business: "Dark Kitchen 'Sabor Criollo' · Surco",
        rating: 5,
        date: "Hace 3 semanas",
        serviceTitle: "Calculadora de Receta Estándar y Margen de Ganancia",
        comment: "Alicia descubrió que en dos de nuestros platos estábamos perdiendo plata por no considerar la merma de la carne. Nos ahorró miles de soles.",
      },
    ],
  },
  {
    id: "pilar",
    name: "Pilar Mendoza",
    avatarUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=300&auto=format&fit=crop&q=80",
    university: "PUCP",
    career: "Comunicaciones",
    semester: "9.º semestre",
    category: "Marketing Digital",
    priceFrom: 42,
    rating: 4.8,
    reviews: 15,
    headline: "Creación de contenido para TikTok/Reels y copywriting persuasivo para cerrar ventas por chat.",
    bio: "Estudiante de Comunicaciones en la PUCP (9.º ciclo). Creo contenido dinámico que conecta con el público peruano sin sonar acartonado ni aburrido.",
    skills: ["TikTok / Reels", "Copywriting para WhatsApp", "Edición CapCut", "Narrativa de Marca"],
    colegiado: false,
    availableNow: true,
    availabilityStatus: "available",
    availabilityNote: "🟢 Disponible hoy · Responde en menos de 20 min",
    responseTime: "< 20 min",
    completedJobs: 25,
    verifiedStudent: true,
    verifications: {
      carneUniversitario: true,
      identidadDni: true,
      telefonoWhatsapp: true,
      cuentaEscrow: true,
      fechaVerificacion: "14 de Junio 2026",
      universidadConstancia: "PUCP - Verificación Vigente",
    },
    tags: ["reels tiktok", "tiktok", "reels", "copywriting", "marketing", "ventas whatsapp"],
    initials: "PM",
    avatarBg: "from-orange-700 to-rose-700",
    services: [
      {
        id: "srv-p1",
        title: "Pack 10 Guiones Virales para TikTok con Audio Tendencia",
        priceFrom: 42,
        deliveryDays: "3 días",
        popular: true,
        description: "10 guiones paso a paso indicando qué decir, qué mostrar en pantalla y qué texto colocar para llamar la atención.",
        deliverables: [
          "Documento PDF con 10 guiones y ganchos",
          "Enlaces directos a audios en tendencia en TikTok",
          "Guía de respuestas rápidas para WhatsApp",
        ],
      },
    ],
    portfolio: [
      {
        id: "pilar-1",
        title: "Estrategia de 10 Videos Virales para TikTok",
        category: "Video Short-Form",
        tag: "+150k Vistas",
        gradient: "from-rose-900 via-orange-800 to-amber-900",
        accentColor: "#FB923C",
        iconType: "ad",
        deliverables: ["10 guiones paso a paso con tomas y audio en tendencia", "Plantilla de respuestas rápidas para WhatsApp", "Optimización de biografía con link"],
        clientQuote: "Un solo video nos trajo más de 80 cotizaciones en un fin de semana.",
        clientName: "Academia de Manejo Los Olivos",
        timeSpent: "4 días",
      },
    ],
    reviewsList: [
      {
        id: "rev-p1",
        author: "Carlos Méndez",
        business: "Academia de Manejo · Los Olivos",
        rating: 5,
        date: "Hace 1 mes",
        serviceTitle: "Pack 10 Guiones Virales para TikTok con Audio Tendencia",
        comment: "Uno de los guiones que nos preparó Pilar se viralizó y tuvimos que contratar un chofer extra de tantas clases que vendimos.",
      },
    ],
  },
  {
    id: "ines",
    name: "Inés Vargas",
    avatarUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&auto=format&fit=crop&q=80",
    university: "UNALM",
    career: "Diseño Gráfico",
    semester: "6.º semestre",
    category: "Diseño Gráfico",
    priceFrom: 32,
    rating: 4.8,
    reviews: 13,
    headline: "Packaging ecológico, etiquetas para botellas y cosmética natural con entregables en 72 h.",
    bio: "Estudiante de Diseño en la Universidad Nacional Agraria La Molina (UNALM). Especialista en diseño de empaques sostenibles, papel kraft y sellos para productos orgánicos y cosmética.",
    skills: ["Packaging Sostenible", "Diseño Ecológico", "Illustrator", "Sellos y Troqueles"],
    colegiado: false,
    availableNow: true,
    availabilityStatus: "available",
    availabilityNote: "🟢 Disponible hoy · Responde en menos de 1 hora",
    responseTime: "< 1 hora",
    completedJobs: 19,
    verifiedStudent: true,
    verifications: {
      carneUniversitario: true,
      identidadDni: true,
      telefonoWhatsapp: true,
      cuentaEscrow: true,
      fechaVerificacion: "22 de Abril 2026",
      universidadConstancia: "UNALM - Carné SUNEDU Activo",
    },
    tags: ["packaging comida", "packaging", "etiquetas", "diseño", "logo", "ecológico"],
    initials: "IV",
    avatarBg: "from-emerald-800 to-teal-900",
    services: [
      {
        id: "srv-i1",
        title: "Diseño de Fajilla Kraft & Sello Ecológico",
        priceFrom: 32,
        deliveryDays: "48 horas",
        popular: true,
        description: "Diseño rústico y elegante para jabones, velas y alimentos en envases biodegradables.",
        deliverables: [
          "Archivo vectorial SVG/PDF listo para imprenta",
          "Arte para confección de sello de jebe",
          "Guía de proveedores locales recomendados",
        ],
      },
    ],
    portfolio: [
      {
        id: "ines-1",
        title: "Línea de Empaque Jabones Artesanales",
        category: "Packaging Sostenible",
        tag: "Cajas Kraft",
        gradient: "from-emerald-950 via-green-900 to-teal-950",
        accentColor: "#6EE7B7",
        iconType: "photo",
        deliverables: ["Diseño de fajilla en papel kraft", "Sello de goma vectorizado", "Ficha técnica para proveedor local"],
        clientQuote: "Gran ojo para productos naturales y entregó antes del plazo.",
        clientName: "Kallpa Cosmética",
        timeSpent: "3 días",
      },
    ],
    reviewsList: [
      {
        id: "rev-i1",
        author: "Patricia Luna",
        business: "Kallpa Cosmética Natural · Miraflores",
        rating: 5,
        date: "Hace 2 semanas",
        serviceTitle: "Diseño de Fajilla Kraft & Sello Ecológico",
        comment: "Inés entendió a la perfección la vibra ecológica de nuestra marca. El sello quedó hermoso.",
      },
    ],
  },
  {
    id: "jorge",
    name: "Jorge Calderón",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80",
    university: "UNMSM",
    career: "Ingeniería de Sistemas",
    semester: "5.º semestre",
    category: "Desarrollo Web",
    priceFrom: 40,
    rating: 4.7,
    reviews: 8,
    headline: "Páginas web en WordPress fáciles de auto-administrar para negocios locales y profesionales.",
    bio: "Estudiante de Sistemas en San Marcos (5.º ciclo). Creo páginas web en WordPress con Elementor Pro para consultorios, estudios contables y negocios que quieren actualizar sus propios textos sin depender de un programador.",
    skills: ["WordPress", "Elementor", "WooCommerce", "Hosting cPanel", "Seguridad Web"],
    colegiado: false,
    availableNow: true,
    availabilityStatus: "available",
    availabilityNote: "🟢 Disponible hoy · Responde en menos de 2 horas",
    responseTime: "< 2 horas",
    completedJobs: 11,
    verifiedStudent: true,
    verifications: {
      carneUniversitario: true,
      identidadDni: true,
      telefonoWhatsapp: true,
      cuentaEscrow: true,
      fechaVerificacion: "30 de Mayo 2026",
      universidadConstancia: "UNMSM - FISI Matrícula Activa",
    },
    tags: ["wordpress", "página web", "sitio web", "web", "autoadministrable"],
    initials: "JC",
    avatarBg: "from-slate-700 to-blue-800",
    services: [
      {
        id: "srv-j1",
        title: "Sitio Web Auto-administrable en WordPress",
        priceFrom: 40,
        deliveryDays: "5 días",
        popular: true,
        description: "Instalación, diseño de 4 secciones y configuración de seguridad con panel amigable.",
        deliverables: [
          "Web en vivo en tu hosting",
          "Formulario de contacto con aviso al correo",
          "Video tutorial para editar textos y fotos",
        ],
      },
    ],
    portfolio: [
      {
        id: "jorge-1",
        title: "Sitio Web para Estudio Contable",
        category: "WordPress",
        tag: "Auto-Administrable",
        gradient: "from-slate-900 via-blue-950 to-slate-800",
        accentColor: "#93C5FD",
        iconType: "web",
        deliverables: ["Página de servicios y contacto", "Blog para artículos tributarios", "Capacitación de 30 min para actualizar contenidos"],
        clientName: "Estudio Asesores SAC",
        timeSpent: "5 días",
      },
    ],
    reviewsList: [
      {
        id: "rev-j1",
        author: "CPC Daniel Flores",
        business: "Flores & Asesores Contables · Lince",
        rating: 4.8,
        date: "Hace 1 mes",
        serviceTitle: "Sitio Web Auto-administrable en WordPress",
        comment: "Excelente servicio de Jorge. Muy claro para explicar el funcionamiento del panel.",
      },
    ],
  },
  {
    id: "nuria",
    name: "Nuria Castro",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80",
    university: "UPC",
    career: "Traducción e Interpretación",
    semester: "Egresado/a",
    category: "Idiomas",
    priceFrom: 48,
    rating: 5.0,
    reviews: 24,
    headline: "Traducción legal de contratos, términos de servicio web y clases de inglés para negociaciones.",
    bio: "Recién egresada de Traducción e Interpretación en la UPC. Traduzco contratos comerciales, términos y condiciones web y documentos empresariales con estricta confidencialidad y precisión técnica.",
    skills: ["Traducción Legal", "Términos Web / SaaS", "Inglés Jurídico", "NDA Confidencial"],
    colegiado: false,
    availableNow: false,
    availabilityStatus: "busy",
    availabilityNote: "🔴 Ocupada hasta el 30 de Agosto (Agenda cerrada)",
    responseTime: "< 3 horas",
    completedJobs: 35,
    verifiedStudent: true,
    verifications: {
      carneUniversitario: true,
      identidadDni: true,
      telefonoWhatsapp: true,
      cuentaEscrow: true,
      fechaVerificacion: "10 de Mayo 2026",
      universidadConstancia: "UPC - Constancia de Egresado",
    },
    tags: ["traducción", "inglés para negocios", "clases de inglés", "contratos", "idiomas"],
    initials: "NC",
    avatarBg: "from-indigo-700 to-blue-800",
    services: [
      {
        id: "srv-n1",
        title: "Traducción de Términos de Servicio y Privacidad Web",
        priceFrom: 48,
        deliveryDays: "3 días",
        popular: true,
        description: "Traducción formal adaptada a la legislación digital peruana e internacional.",
        deliverables: [
          "Documento bilingüe en Word/PDF",
          "Glosario de términos digitales",
          "Declaración de fidelidad de traducción",
        ],
      },
    ],
    portfolio: [
      {
        id: "nuria-1",
        title: "Términos & Condiciones y Política de Privacidad EN–ES",
        category: "Traducción Técnica",
        tag: "Web & SaaS",
        gradient: "from-indigo-950 via-slate-900 to-blue-900",
        accentColor: "#A5B4FC",
        iconType: "translate",
        deliverables: ["Traducción jurídica contextualizada a Perú y EE.UU.", "Glosario de términos digitales", "Certificado de precisión de traducción"],
        clientQuote: "Excelente nivel técnico y puntualidad impecable.",
        clientName: "Fintech Startup Lima",
        timeSpent: "3 días",
      },
    ],
    reviewsList: [
      {
        id: "rev-n1",
        author: "Luis Barnechea",
        business: "Fintech Lima SAC · San Isidro",
        rating: 5,
        date: "Hace 3 semanas",
        serviceTitle: "Traducción de Términos de Servicio y Privacidad Web",
        comment: "Impecable traducción legal para nuestra app de pagos. Cumplió con creces.",
      },
    ],
  },
  {
    id: "kevin",
    name: "Kevin Ramos",
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80",
    university: "UTP",
    career: "Administración de Empresas",
    semester: "4.º semestre",
    category: "Administración",
    priceFrom: 28,
    rating: 4.5,
    reviews: 9,
    headline: "Armado de plantillas de cotización, seguimiento de clientes y automatización con WhatsApp Business.",
    bio: "Estudiante de Administración en la UTP (4.º ciclo). Te ayudo a configurar WhatsApp Business con respuestas rápidas, catálogo y etiquetas para que ningún cliente se quede sin respuesta.",
    skills: ["WhatsApp Business", "Plantillas de Cotización", "Atención al Cliente", "Excel Básico"],
    colegiado: false,
    availableNow: true,
    availabilityStatus: "available",
    availabilityNote: "🟢 Disponible hoy · Responde en menos de 15 min",
    responseTime: "< 15 min",
    completedJobs: 14,
    verifiedStudent: true,
    verifications: {
      carneUniversitario: true,
      identidadDni: true,
      telefonoWhatsapp: true,
      cuentaEscrow: true,
      fechaVerificacion: "25 de Mayo 2026",
      universidadConstancia: "UTP - Matrícula 2026",
    },
    tags: ["excel", "cotizaciones", "whatsapp", "ventas", "admin"],
    initials: "KR",
    avatarBg: "from-lime-700 to-green-800",
    services: [
      {
        id: "srv-k1",
        title: "Configuración Integral de WhatsApp Business",
        priceFrom: 28,
        deliveryDays: "24 horas",
        popular: true,
        description: "Horarios, mensaje de bienvenida, 15 respuestas rápidas y catálogo de productos con fotos.",
        deliverables: [
          "WhatsApp configurado y probado",
          "Listado de etiquetas para clasificar prospectos",
          "Plantilla Excel para seguimiento de cotizaciones",
        ],
      },
    ],
    portfolio: [
      {
        id: "kevin-1",
        title: "Catálogo de Respuestas Rápidas WhatsApp",
        category: "Atención al Cliente",
        tag: "WhatsApp Business",
        gradient: "from-emerald-950 via-lime-900 to-slate-900",
        accentColor: "#BEF264",
        iconType: "app",
        deliverables: ["15 respuestas guardadas para objeciones frecuentes", "Etiquetas para clasificar clientes en embudo", "Enlace directo a catálogo"],
        clientName: "Importadora de Calzado",
        timeSpent: "2 días",
      },
    ],
    reviewsList: [
      {
        id: "rev-k1",
        author: "Sonia G.",
        business: "Calzado Infantil · Ceres Ate",
        rating: 4.6,
        date: "Hace 1 mes",
        serviceTitle: "Configuración Integral de WhatsApp Business",
        comment: "Muy útil. Ahora mi negocio responde solo cuando no estoy disponible.",
      },
    ],
  },
  {
    id: "paolo",
    name: "Paolo Gutiérrez",
    avatarUrl: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=300&auto=format&fit=crop&q=80",
    university: "UNI",
    career: "Diseño Gráfico",
    semester: "4.º semestre",
    category: "Diseño Gráfico",
    priceFrom: 30,
    rating: 4.7,
    reviews: 10,
    headline: "Prototipos en Figma y diseño de interfaces web/móvil para validar ideas de negocio rápido.",
    bio: "Estudiante de Diseño en la UNI (4.º ciclo). Creo prototipos navegables en Figma para que puedas mostrarle tu idea de app o sistema a clientes o inversores antes de gastar en programación.",
    skills: ["Figma", "UI/UX Design", "Wireframing", "Design Systems", "Prototyping"],
    colegiado: false,
    availableNow: true,
    availabilityStatus: "available",
    availabilityNote: "🟢 Disponible hoy · Responde en menos de 1 hora",
    responseTime: "< 1 hora",
    completedJobs: 12,
    verifiedStudent: true,
    verifications: {
      carneUniversitario: true,
      identidadDni: true,
      telefonoWhatsapp: true,
      cuentaEscrow: true,
      fechaVerificacion: "18 de Mayo 2026",
      universidadConstancia: "UNI - Carné Universitario Activo",
    },
    tags: ["figma", "ui", "prototipo", "diseñador de logo", "diseño", "app"],
    initials: "PG",
    avatarBg: "from-blue-900 to-indigo-800",
    services: [
      {
        id: "srv-pg1",
        title: "Prototipo Interactivo en Figma (Hasta 8 Pantallas)",
        priceFrom: 30,
        deliveryDays: "4 días",
        popular: true,
        description: "Diseño visual moderno en Figma con botones cliqueables para probar el flujo en celular.",
        deliverables: [
          "Archivo Figma editable (.fig)",
          "Enlace interactivo para probar en cualquier celular",
          "Kit de colores y componentes básicos",
        ],
      },
    ],
    portfolio: [
      {
        id: "paolo-1",
        title: "Prototipo Navegable de App Delivery",
        category: "UI/UX en Figma",
        tag: "Figma Prototipo",
        gradient: "from-blue-950 via-indigo-900 to-slate-900",
        accentColor: "#60A5FA",
        iconType: "app",
        deliverables: ["Flujo de usuario completo de 8 pantallas", "Enlace interactivo para probar en celular", "Guía de estilos (colores y tipografías)"],
        clientName: "Emprendimiento Dark Kitchen",
        timeSpent: "5 días",
      },
    ],
    reviewsList: [
      {
        id: "rev-pg1",
        author: "Guillermo Arce",
        business: "App 'PideRápido' · Surquillo",
        rating: 4.8,
        date: "Hace 3 semanas",
        serviceTitle: "Prototipo Interactivo en Figma (Hasta 8 Pantallas)",
        comment: "El prototipo en Figma nos permitió validar el flujo de compras con usuarios reales. Muy creativo Paolo.",
      },
    ],
  },
];

export const REVIEWS = [
  {
    quote:
      "Pedí un logo y un pack de posts. Camila me explicó como en una mini-sustentación: opciones, por qué y ajustes. El pago se liberó cuando ya tenía todo en Canva.",
    name: "Rosa M.",
    meta: "Cevichería · Magdalena",
  },
  {
    quote:
      "Necesitaba una landing para mi taller de soldadura. Diego la dejó lista en una semana y el escrow me dio tranquilidad: no pagué hasta verla publicada.",
    name: "Héctor V.",
    meta: "MYPE · Villa El Salvador",
  },
  {
    quote:
      "Valeria armó el calendario y las primeras ads. Gasté poco y por fin supe qué publicar. Se nota que estudia marketing de verdad.",
    name: "Andrea C.",
    meta: "Tienda de accesorios · SJL",
  },
];


