export const CATEGORIES = [
  {
    id: "diseno",
    title: "Diseño gráfico",
    blurb: "Marcas, posts, presentaciones y piezas para tu negocio.",
    icon: "◇",
  },
  {
    id: "web",
    title: "Desarrollo web",
    blurb: "Landings, tiendas y automatizaciones con código real.",
    icon: "</>",
  },
  {
    id: "marketing",
    title: "Marketing digital",
    blurb: "Campañas, contenido y analítica para vender más.",
    icon: "↗",
  },
  {
    id: "admin",
    title: "Administración",
    blurb: "Excel, trámites, reportes y orden operativo.",
    icon: "▣",
  },
  {
    id: "idiomas",
    title: "Idiomas",
    blurb: "Traducción, clases y revisión de textos.",
    icon: "あ",
  },
] as const;

export const UNIVERSITIES = [
  "UTP",
  "UPC",
  "PUCP",
  "UNMSM",
  "UNI",
  "USIL",
  "Universidad de Lima",
  "UNALM",
  "Otra universidad",
];

export const CAREERS = [
  "Diseño gráfico",
  "Ingeniería de Sistemas",
  "Ingeniería de Software",
  "Marketing",
  "Administración",
  "Comunicaciones",
  "Traducción e Interpretación",
  "Economía",
  "Otra",
];

export const STUDENT_STEPS = [
  { n: 1, label: "Rol" },
  { n: 2, label: "Datos" },
  { n: 3, label: "Carné" },
  { n: 4, label: "Verificación" },
];

export type PortfolioShot = {
  label: string;
  bg: string;
  accent: string;
};

export type Talent = {
  id: string;
  name: string;
  university: string;
  career: string;
  semester: string;
  category: string;
  priceFrom: number;
  rating: number;
  reviews: number;
  headline: string;
  colegiado: boolean;
  availableNow: boolean;
  tags: string[];
  initials: string;
  avatar: string;
  portfolio: PortfolioShot[];
};

const shot = (label: string, bg: string, accent: string): PortfolioShot => ({
  label,
  bg,
  accent,
});

export const TALENT: Talent[] = [
  {
    id: "camila",
    name: "Camila Rojas",
    university: "UTP",
    career: "Diseño gráfico",
    semester: "7.º semestre",
    category: "Diseño gráfico",
    priceFrom: 45,
    rating: 4.9,
    reviews: 18,
    headline: "Identidad visual para MYPES que recién empiezan a vender online.",
    colegiado: false,
    availableNow: true,
    tags: ["logo", "diseñador de logo", "marca", "branding", "posts"],
    initials: "CR",
    avatar: "#2563EB",
    portfolio: [
      shot("Logo ceviche", "#1E3A8A", "#F97316"),
      shot("Pack stories", "#F97316", "#FFFFFF"),
      shot("Carta A4", "#F3F4F6", "#2563EB"),
    ],
  },
  {
    id: "diego",
    name: "Diego Palacios",
    university: "UNI",
    career: "Ingeniería de Sistemas",
    semester: "9.º semestre",
    category: "Desarrollo web",
    priceFrom: 60,
    rating: 4.8,
    reviews: 12,
    headline: "Landings rápidas y formularios que sí llegan a WhatsApp.",
    colegiado: false,
    availableNow: true,
    tags: ["página web", "landing", "web", "sitio", "wordpress"],
    initials: "DP",
    avatar: "#1D4ED8",
    portfolio: [
      shot("Landing taller", "#0F172A", "#22C55E"),
      shot("Formulario", "#2563EB", "#FFFFFF"),
      shot("Checkout", "#F3F4F6", "#F97316"),
    ],
  },
  {
    id: "valeria",
    name: "Valeria Quispe",
    university: "PUCP",
    career: "Marketing",
    semester: "8.º semestre",
    category: "Marketing digital",
    priceFrom: 50,
    rating: 5.0,
    reviews: 9,
    headline: "Calendario de contenido y Meta Ads con presupuesto chico.",
    colegiado: false,
    availableNow: false,
    tags: ["ads", "meta", "contenido", "redes", "marketing"],
    initials: "VQ",
    avatar: "#EA580C",
    portfolio: [
      shot("Calendario", "#9A3412", "#FDBA74"),
      shot("Ads set", "#F97316", "#FFFFFF"),
      shot("Reporte", "#F3F4F6", "#1F2937"),
    ],
  },
  {
    id: "renzo",
    name: "Renzo Huamán",
    university: "UNMSM",
    career: "Administración",
    semester: "10.º semestre",
    category: "Administración",
    priceFrom: 35,
    rating: 4.7,
    reviews: 21,
    headline: "Kardex, Excel y reportes listos para SUNAT sin drama.",
    colegiado: false,
    availableNow: true,
    tags: ["excel", "sunat", "kardex", "contabilidad", "admin"],
    initials: "RH",
    avatar: "#16A34A",
    portfolio: [
      shot("Kardex", "#14532D", "#86EFAC"),
      shot("Flujo caja", "#22C55E", "#FFFFFF"),
      shot("Dashboard", "#F3F4F6", "#2563EB"),
    ],
  },
  {
    id: "lucia",
    name: "Lucía Ferrer",
    university: "UPC",
    career: "Traducción e Interpretación",
    semester: "6.º semestre",
    category: "Idiomas",
    priceFrom: 40,
    rating: 4.9,
    reviews: 14,
    headline: "Traducción EN–ES y clases de inglés para atender clientes.",
    colegiado: false,
    availableNow: true,
    tags: ["inglés", "clases de inglés", "traducción", "english", "idiomas"],
    initials: "LF",
    avatar: "#7C3AED",
    portfolio: [
      shot("Menú EN", "#4C1D95", "#C4B5FD"),
      shot("Clase 1:1", "#2563EB", "#FFFFFF"),
      shot("Ficha técnica", "#F3F4F6", "#F97316"),
    ],
  },
  {
    id: "mateo",
    name: "Mateo Salas",
    university: "USIL",
    career: "Ingeniería de Software",
    semester: "Egresado/a",
    category: "Desarrollo web",
    priceFrom: 55,
    rating: 4.6,
    reviews: 7,
    headline: "Tienda simple + pasarela. Entrego demo en 7 días.",
    colegiado: false,
    availableNow: false,
    tags: ["página web", "tienda", "ecommerce", "web", "pasarela"],
    initials: "MS",
    avatar: "#1E40AF",
    portfolio: [
      shot("Tienda demo", "#1E3A8A", "#93C5FD"),
      shot("Carrito", "#F97316", "#FFFFFF"),
      shot("Admin", "#F3F4F6", "#22C55E"),
    ],
  },
  {
    id: "sofia",
    name: "Sofía León",
    university: "Universidad de Lima",
    career: "Diseño gráfico",
    semester: "5.º semestre",
    category: "Diseño gráfico",
    priceFrom: 38,
    rating: 4.5,
    reviews: 11,
    headline: "Logos simples y piezas para feria. Entrego en 72 h.",
    colegiado: false,
    availableNow: true,
    tags: ["logo", "diseñador de logo", "feria", "flyer", "impresos"],
    initials: "SL",
    avatar: "#DB2777",
    portfolio: [
      shot("Logo feria", "#9D174D", "#FBCFE8"),
      shot("Flyer A5", "#F97316", "#FFFFFF"),
      shot("Sticker", "#F3F4F6", "#2563EB"),
    ],
  },
  {
    id: "andres",
    name: "Andrés Paredes",
    university: "UNI",
    career: "Ingeniería de Software",
    semester: "8.º semestre",
    category: "Desarrollo web",
    priceFrom: 70,
    rating: 4.9,
    reviews: 16,
    headline: "Webs a medida con React. Ideal si ya tienes Figma.",
    colegiado: false,
    availableNow: true,
    tags: ["página web", "react", "web", "frontend", "figma"],
    initials: "AP",
    avatar: "#0F766E",
    portfolio: [
      shot("App reserva", "#134E4A", "#5EEAD4"),
      shot("UI kit", "#2563EB", "#FFFFFF"),
      shot("API", "#F3F4F6", "#1F2937"),
    ],
  },
  {
    id: "pilar",
    name: "Pilar Mendoza",
    university: "PUCP",
    career: "Comunicaciones",
    semester: "9.º semestre",
    category: "Marketing digital",
    priceFrom: 42,
    rating: 4.4,
    reviews: 8,
    headline: "Guiones de Reels y tono de marca para tiendas de barrio.",
    colegiado: false,
    availableNow: true,
    tags: ["reels", "copy", "redes", "contenido", "marketing"],
    initials: "PM",
    avatar: "#C2410C",
    portfolio: [
      shot("Reels pack", "#7C2D12", "#FDBA74"),
      shot("Copy", "#F97316", "#FFFFFF"),
      shot("Mood", "#F3F4F6", "#2563EB"),
    ],
  },
  {
    id: "kevin",
    name: "Kevin Ramos",
    university: "UTP",
    career: "Administración",
    semester: "4.º semestre",
    category: "Administración",
    priceFrom: 28,
    rating: 4.3,
    reviews: 6,
    headline: "Armado de cotizaciones, seguimiento y WhatsApp Business.",
    colegiado: false,
    availableNow: true,
    tags: ["whatsapp", "cotizaciones", "admin", "ventas", "excel"],
    initials: "KR",
    avatar: "#365314",
    portfolio: [
      shot("Plantilla", "#3F6212", "#BEF264"),
      shot("Pipeline", "#22C55E", "#FFFFFF"),
      shot("Agenda", "#F3F4F6", "#F97316"),
    ],
  },
  {
    id: "nuria",
    name: "Nuria Castro",
    university: "UPC",
    career: "Traducción e Interpretación",
    semester: "Egresado/a",
    category: "Idiomas",
    priceFrom: 48,
    rating: 5.0,
    reviews: 22,
    headline: "Clases de inglés conversacional para atender turistas.",
    colegiado: false,
    availableNow: false,
    tags: ["inglés", "clases de inglés", "conversación", "turistas", "idiomas"],
    initials: "NC",
    avatar: "#1D4ED8",
    portfolio: [
      shot("Syllabus", "#1E3A8A", "#93C5FD"),
      shot("Roleplay", "#22C55E", "#FFFFFF"),
      shot("Audio", "#F3F4F6", "#F97316"),
    ],
  },
  {
    id: "bruno",
    name: "Bruno Aliaga",
    university: "USIL",
    career: "Marketing",
    semester: "7.º semestre",
    category: "Marketing digital",
    priceFrom: 55,
    rating: 4.2,
    reviews: 5,
    headline: "Google Ads local: “cerca de mí” para talleres y clínicas.",
    colegiado: false,
    availableNow: true,
    tags: ["google ads", "seo local", "marketing", "clics", "campaña"],
    initials: "BA",
    avatar: "#B45309",
    portfolio: [
      shot("Campaña", "#78350F", "#FCD34D"),
      shot("Keywords", "#2563EB", "#FFFFFF"),
      shot("KPI", "#F3F4F6", "#22C55E"),
    ],
  },
  {
    id: "ines",
    name: "Inés Vargas",
    university: "UNALM",
    career: "Diseño gráfico",
    semester: "6.º semestre",
    category: "Diseño gráfico",
    priceFrom: 32,
    rating: 4.8,
    reviews: 13,
    headline: "Packaging y etiquetas para alimentos y cosmética natural.",
    colegiado: false,
    availableNow: true,
    tags: ["packaging", "etiqueta", "logo", "producto", "diseño"],
    initials: "IV",
    avatar: "#047857",
    portfolio: [
      shot("Etiqueta", "#064E3B", "#6EE7B7"),
      shot("Caja", "#F97316", "#FFFFFF"),
      shot("Mockup", "#F3F4F6", "#1F2937"),
    ],
  },
  {
    id: "jorge",
    name: "Jorge Calderón",
    university: "UNMSM",
    career: "Ingeniería de Sistemas",
    semester: "5.º semestre",
    category: "Desarrollo web",
    priceFrom: 40,
    rating: 4.1,
    reviews: 4,
    headline: "Páginas en WordPress para catálogos y reservas.",
    colegiado: false,
    availableNow: true,
    tags: ["wordpress", "página web", "catálogo", "reservas", "web"],
    initials: "JC",
    avatar: "#334155",
    portfolio: [
      shot("Catálogo", "#0F172A", "#94A3B8"),
      shot("Reserva", "#2563EB", "#FFFFFF"),
      shot("Blog", "#F3F4F6", "#F97316"),
    ],
  },
  {
    id: "alicia",
    name: "Alicia Chávez",
    university: "PUCP",
    career: "Economía",
    semester: "8.º semestre",
    category: "Administración",
    priceFrom: 45,
    rating: 4.6,
    reviews: 10,
    headline: "Costos, precios de venta y flujo para ferias y delivery.",
    colegiado: false,
    availableNow: false,
    tags: ["costos", "precios", "excel", "finanzas", "admin"],
    initials: "AC",
    avatar: "#0F766E",
    portfolio: [
      shot("Costeo", "#115E59", "#99F6E4"),
      shot("Precios", "#22C55E", "#FFFFFF"),
      shot("Flujo", "#F3F4F6", "#2563EB"),
    ],
  },
  {
    id: "marco",
    name: "Marco Tello",
    university: "UTP",
    career: "Traducción e Interpretación",
    semester: "3.º semestre",
    category: "Idiomas",
    priceFrom: 25,
    rating: 4.0,
    reviews: 3,
    headline: "Clases de inglés básico y corrección de textos de carta.",
    colegiado: false,
    availableNow: true,
    tags: ["inglés", "clases de inglés", "básico", "corrección", "idiomas"],
    initials: "MT",
    avatar: "#4338CA",
    portfolio: [
      shot("Nivel A1", "#312E81", "#A5B4FC"),
      shot("Carta", "#F97316", "#FFFFFF"),
      shot("Quiz", "#F3F4F6", "#22C55E"),
    ],
  },
  {
    id: "elena",
    name: "Elena Ortiz",
    university: "Universidad de Lima",
    career: "Comunicaciones",
    semester: "Egresado/a",
    category: "Marketing digital",
    priceFrom: 65,
    rating: 4.7,
    reviews: 19,
    headline: "Estrategia 90 días: oferta, canal y medición para MYPE.",
    colegiado: false,
    availableNow: true,
    tags: ["estrategia", "marketing", "plan", "redes", "mype"],
    initials: "EO",
    avatar: "#9A3412",
    portfolio: [
      shot("Plan 90d", "#7C2D12", "#FED7AA"),
      shot("Embudo", "#2563EB", "#FFFFFF"),
      shot("OKR", "#F3F4F6", "#22C55E"),
    ],
  },
  {
    id: "paolo",
    name: "Paolo Gutiérrez",
    university: "UNI",
    career: "Diseño gráfico",
    semester: "4.º semestre",
    category: "Diseño gráfico",
    priceFrom: 30,
    rating: 4.4,
    reviews: 9,
    headline: "UI de apps simples y prototipos para validar la idea.",
    colegiado: false,
    availableNow: true,
    tags: ["ui", "prototipo", "app", "figma", "diseño"],
    initials: "PG",
    avatar: "#1E40AF",
    portfolio: [
      shot("Wireframe", "#1E3A8A", "#BFDBFE"),
      shot("Hi-fi", "#F97316", "#FFFFFF"),
      shot("Flujo", "#F3F4F6", "#22C55E"),
    ],
  },
];

export const REVIEWS = [
  {
    quote:
      "Pedí un logo y un pack de posts. Camila me explicó como en una mini-sustentación: opciones, por qué y ajustes. El pago se liberó cuando ya tenía todo en Canva.",
    name: "Rosa M.",
    meta: "Cevichería · Magdalena",
  },
  {
    quote:
      "Necesitaba una landing para mi taller de soldadura. Diego la dejó lista en una semana y el escrow me dio tranquilidad: no pagué hasta verla publicada.",
    name: "Héctor V.",
    meta: "MYPE · Villa El Salvador",
  },
  {
    quote:
      "Valeria armó el calendario y las primeras ads. Gasté poco y por fin supe qué publicar. Se nota que estudia marketing de verdad.",
    name: "Andrea C.",
    meta: "Tienda de accesorios · SJL",
  },
];
